### ISSUE TITLE
AttributeError: 'EmptyCommentGenerator' object has no attribute 'functions_called'

### ISSUE THREAD

**Issue by seth1002** [zeropointdynamics/zelos#121]
**Describe the bug**
18:18:50:engine____:ERROR_:Exception while trying to close Zelos
Traceback (most recent call last):
  File "/home/aaaaa/Envs/zelos/lib/python3.7/site-packages/zelos-0.1.1.dev0-py3.7.egg/zelos/engine.py", line 603, in close
    closure()
  File "/home/aaaaa/Envs/zelos/lib/python3.7/site-packages/zelos-0.1.1.dev0-py3.7.egg/zelos/ext/plugins/overlay/overlay.py", line 71, in closure
    f, trace=self.export_trace, mem=self.export_mem
  File "/home/aaaaa/Envs/zelos/lib/python3.7/site-packages/zelos-0.1.1.dev0-py3.7.egg/zelos/ext/plugins/overlay/overlay.py", line 212, in export
    for addr in self.zelos.plugins.trace.functions_called.keys():
  File "/home/aaaaa/Envs/zelos/lib/python3.7/site-packages/zelos-0.1.1.dev0-py3.7.egg/zelos/ext/plugins/trace.py", line 133, in functions_called
    return self.comment_generator.functions_called
AttributeError: 'EmptyCommentGenerator' object has no attribute 'functions_called'

it happens when i use "--export_trace --inst --fasttrace".
sorry, I can't provide relevant test file, can you please check this issue?

**Comment by seth1002** [comment]
thank you, exception has been fixed, but overlay file still empty.  
there is only entry point node info.

DISAS
{
    "comments": [],
    "entrypoint": 4194912,
    "functions": [],
    "sections": []
}
~

**Comment by rcourt** [comment]
I will take a look. Thanks for the info.

**Comment by rcourt** [comment]
@seth1002 Is there any binary you can provide that replicates this issue? I can't seem to get an empty overlay file with any our test files.

**Comment by seth1002** [comment]
@rcourt Sorry, i pulled wrong version, this bug have been fixed. Thank you!
