### ISSUE TITLE
Unresolved symbols when using musl interpreter

### ISSUE THREAD

**Issue by smeng9** [zeropointdynamics/zelos#135]
**Describe the bug**
I tried to run a dynamically linked binary compiled against musl, but zelos cannot load the program correctly

**To Reproduce**
1. Download the following musl binary `uname` with ld-musl-x86_64.so.1 (You can also obtain from Alpine Linux distribution)
[musl_binary.zip](https://github.com/zeropointdynamics/zelos/files/5737353/musl_binary.zip)
2. Put ld-musl-x86_64.so.1 in /lib folder
3. `uname` should be able to run correctly when directly called in terminal
4. `uname` cannot be run when calling `zelos uname`

**Expected behavior**
The interpreter should be found and loaded, and all symbols should be resolved.

**Screenshots**
zelos uname --mount=x86,/lib/ld-musl-x86_64.so.1,/lib/ld-musl-x86_64.so.1
16:28:00:parse_____:NOTICE:No default interpreter for this arch
Traceback (most recent call last):
  File "/home/shaoyu/.local/bin/zelos", line 8, in <module>
    sys.exit(main())
  File "/home/shaoyu/.local/lib/python3.8/site-packages/zelos/__main__.py", line 23, in main
    z = ZelosCmdline(sys.argv[1:])
  File "/home/shaoyu/.local/lib/python3.8/site-packages/zelos/api/zelos_api.py", line 721, in __init__
    self._setup(config)
  File "/home/shaoyu/.local/lib/python3.8/site-packages/zelos/api/zelos_api.py", line 78, in _setup
    e = Engine(config=config, api=self)
  File "/home/shaoyu/.local/lib/python3.8/site-packages/zelos/engine.py", line 123, in __init__
    self.load_executable(binary, entrypoint_override=config.startat)
  File "/home/shaoyu/.local/lib/python3.8/site-packages/zelos/engine.py", line 315, in load_executable
    file = self._first_parse(module_path)
  File "/home/shaoyu/.local/lib/python3.8/site-packages/zelos/engine.py", line 289, in _first_parse
    return self._parse_file_data(module_path, file_data)
  File "/home/shaoyu/.local/lib/python3.8/site-packages/zelos/engine.py", line 297, in _parse_file_data
    parsed_file = self.os_plugins.parse(filename, filedata)
  File "/home/shaoyu/.local/lib/python3.8/site-packages/zelos/plugin/plugin.py", line 168, in parse
    parsed_file = os_plugin.parse(path, binary)
  File "/home/shaoyu/.local/lib/python3.8/site-packages/zelos/ext/platforms/linux/linux.py", line 80, in parse
    parsed_file = LiefELF(self.z.files, path, binary)
  File "/home/shaoyu/.local/lib/python3.8/site-packages/zelos/ext/platforms/linux/parse.py", line 33, in __init__
    self.parse(path, binary)
  File "/home/shaoyu/.local/lib/python3.8/site-packages/zelos/ext/platforms/linux/parse.py", line 106, in parse
    for symbol in binary.static_symbols:
AttributeError: 'NoneType' object has no attribute 'static_symbols'

**Additional context**

**Comment by kvalakuzhyzp** [comment]
Thanks @smeng9  for using Zelos!

The reason you are getting this issue is indeed because of a bug in the ordering of when we try to identify the loader vs when we mount files into the filesystem.

If you want to run this file now, you can try using this command:

`zelos ld-musl-x86_64.so.1 dynamic/uname --mount=x86,dynamic/uname,dynamic/uname`

which would be emulating the slightly different command `ld-musl-x86_64.so.1 dynamic/uname` on the command line. 

Let me know if this is an acceptable workaround for the moment.

**Comment by smeng9** [comment]
Yes, switching the order of arguments works for the moment. Thanks!
